/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:52:06 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.CepValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CepValidator_ESTest extends CepValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CepValidator.isSameRegion((String) null, (String) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CepValidator.isCapital("45678901");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CepValidator.isCapital("Sudeste (SP)");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CepValidator.isCapital((String) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CepValidator.isCapital("55555555");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CepValidator.getRegion("99999999");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CepValidator.isSameRegion("88888888", "Sudeste (SP)");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CepValidator.getRegion("77777777");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CepValidator.isSameRegion("66666666", "66666-666");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CepValidator.isSameRegion("45678901", "45678901");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CepValidator.getRegion("32109-876");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CepValidator.getRegion("23456789");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CepValidator.isSameRegion("11111111", (String) null);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CepValidator.getRegion("00000000");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CepValidator.isSameRegion("55555555", "56787-654");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      CepValidator.generateValidCep();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = CepValidator.format("Desconhecida");
      assertEquals("Desconhecida", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = CepValidator.format((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Random.setNextRandom(2147483645);
      String string0 = CepValidator.generateValidCep();
      assertEquals("56787-654", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = CepValidator.removeFormatting((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid("56799012");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      try { 
        CepValidator.validate("55559555");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CEP inv\u00E1lido: padr\u00E3o sequencial ou repetitivo
         //
         verifyException("br.ufjf.ead.validator.CepValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid("00000000");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid("Sudeste (SP)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      boolean boolean0 = CepValidator.isValid("32109-876");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CepValidator cepValidator0 = new CepValidator();
  }
}
