/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:59:56 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.CnpjValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CnpjValidator_ESTest extends CnpjValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = CnpjValidator.isValid("01.234.567/8901-07");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Random.setNextRandom(6);
      String string0 = CnpjValidator.generateValidCnpj();
      assertEquals("67.890.123/4567-80", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      try { 
        CnpjValidator.validate("888888588888W*88");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CNPJ inv\u00E1lido: d\u00EDgitos verificadores incorretos
         //
         verifyException("br.ufjf.ead.validator.CnpjValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = CnpjValidator.isValid("99999999999999");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      boolean boolean0 = CnpjValidator.isValid("6664666666666");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      try { 
        CnpjValidator.validate(" ");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CNPJ n\u00E3o pode ser nulo ou vazio
         //
         verifyException("br.ufjf.ead.validator.CnpjValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      try { 
        CnpjValidator.validate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CNPJ n\u00E3o pode ser nulo ou vazio
         //
         verifyException("br.ufjf.ead.validator.CnpjValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = CnpjValidator.isValid("66646I.66666666%+6");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CnpjValidator cnpjValidator0 = new CnpjValidator();
  }
}
