/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 17:01:02 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.CpfValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CpfValidator_ESTest extends CpfValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = CpfValidator.generateValidCpf();
      assertEquals("012.345.678-90", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = CpfValidator.isValid("ne$q567187n543s98");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = CpfValidator.isValid("012.345.678-90");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      try { 
        CpfValidator.validate("66e666666666");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CPF inv\u00E1lido: todos os d\u00EDgitos s\u00E3o iguais
         //
         verifyException("br.ufjf.ead.validator.CpfValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      try { 
        CpfValidator.validate("/;#RMWk/<D_#|OQ|l");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // CPF deve conter 11 d\u00EDgitos
         //
         verifyException("br.ufjf.ead.validator.CpfValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      boolean boolean0 = CpfValidator.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      boolean boolean0 = CpfValidator.isValid((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      boolean boolean0 = CpfValidator.isValid("66i=6636b`q66166");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CpfValidator cpfValidator0 = new CpfValidator();
  }
}
