/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:53:58 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.CreditCardValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CreditCardValidator_ESTest extends CreditCardValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = CreditCardValidator.isValid("4123456789012349");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = CreditCardValidator.generateTestCard("Xlhv> !h.uRe0");
      assertEquals("4012345678901231", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = CreditCardValidator.generateTestCard("Discover");
      assertEquals("6011012345678908", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = CreditCardValidator.generateTestCard("amex");
      assertEquals("340123456789012", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = CreditCardValidator.generateTestCard("visa");
      assertEquals("4012345678901231", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = CreditCardValidator.generateTestCard("mastercard");
      assertEquals("5501234567890127", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = CreditCardValidator.mask("4012345678901231");
      assertEquals("401234 ****** 1231", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = CreditCardValidator.mask((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = CreditCardValidator.mask("mastercard");
      assertEquals("**** **** **** ****", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = CreditCardValidator.format((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = CreditCardValidator.format("4123456789012349");
      assertEquals("4123 4567 8901 2349", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = CreditCardValidator.getCardBrand("3_538160112345+78");
      assertEquals("JCB", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = CreditCardValidator.getCardBrand("6011012345678908");
      assertNotNull(string0);
      assertEquals("Discover", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = CreditCardValidator.getCardBrand("30260116789012^34562");
      assertNotNull(string0);
      assertEquals("Diners Club", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = CreditCardValidator.getCardBrand("340123456789012");
      assertNotNull(string0);
      assertEquals("American Express", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = CreditCardValidator.getCardBrand("5501234567890127");
      assertEquals("MasterCard", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      try { 
        CreditCardValidator.validate("44412345678901231");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Bandeira do cart\u00E3o n\u00E3o reconhecida
         //
         verifyException("br.ufjf.ead.validator.CreditCardValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      boolean boolean0 = CreditCardValidator.isValid("43026011678901234562");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      boolean boolean0 = CreditCardValidator.isValid("0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      try { 
        CreditCardValidator.validate("340123456789012");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00FAmero do cart\u00E3o inv\u00E1lido (algoritmo de Luhn)
         //
         verifyException("br.ufjf.ead.validator.CreditCardValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      try { 
        CreditCardValidator.validate("*BxCvh'|;!B");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00FAmero do cart\u00E3o deve conter apenas d\u00EDgitos
         //
         verifyException("br.ufjf.ead.validator.CreditCardValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      try { 
        CreditCardValidator.validate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00FAmero do cart\u00E3o n\u00E3o pode ser nulo ou vazio
         //
         verifyException("br.ufjf.ead.validator.CreditCardValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      boolean boolean0 = CreditCardValidator.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CreditCardValidator creditCardValidator0 = new CreditCardValidator();
  }
}
