/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:50:00 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.DateValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateValidator_ESTest extends DateValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("MM-dd-yyyy");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      boolean boolean0 = DateValidator.isInRange("06/02/3481", "25/09/2089", "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = DateValidator.calculateAge("br.ufjf.ead.exception.InvalidDocumentException");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = DateValidator.generateRandomDate(3481, 3481);
      assertEquals("06/02/3481", string0);
      
      String string1 = DateValidator.generateRandomDate(3481, 3481);
      assertEquals("16/05/3481", string1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = DateValidator.isInRange("0602-02-46", "0602-02-46", "0602-02-46");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = DateValidator.isInRange("06/02/3432", "25/09/2052", "25/09/2052");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = DateValidator.calculateAge("06/02/3481");
      assertEquals((-1455), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = DateValidator.calculateAge("0602-00-00");
      assertEquals(2026, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = DateValidator.calculateAge("0602-02-22");
      assertEquals(2003, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = DateValidator.calculateAge("16/05/2087096595");
      assertEquals((-2087094570), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = DateValidator.formatISO("06($ws");
      assertEquals("06($ws", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = DateValidator.formatISO((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = DateValidator.formatISO("06/02/0222");
      assertNotNull(string0);
      assertEquals("0602-02-22", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = DateValidator.formatBrazilian("0602-00-00");
      assertEquals("06/02/0000", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = DateValidator.formatBrazilian((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = DateValidator.formatBrazilian("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = DateValidator.generateRandomDate(0, (-1));
      assertEquals("06/02/0000", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("06/02/2080");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DateValidator.validate("06/02/2001");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("06($ws");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("06/02/3481");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      try { 
        DateValidator.validate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Data n\u00E3o pode ser nula ou vazia
         //
         verifyException("br.ufjf.ead.validator.DateValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      boolean boolean0 = DateValidator.isValid("25/09/2052");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DateValidator dateValidator0 = new DateValidator();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      boolean boolean0 = DateValidator.isInRange("06/02/2001", "16/05/2001", "16/05/2001");
      assertFalse(boolean0);
  }
}
