/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:58:48 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.EmailValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailValidator_ESTest extends EmailValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      boolean boolean0 = EmailValidator.isValid("3@J.eA");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = EmailValidator.format((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = EmailValidator.format("%@-.AA");
      assertEquals("%@-.aa", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      try { 
        EmailValidator.validate("%@..WgfA");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Dom\u00EDnio inv\u00E1lido
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      try { 
        EmailValidator.validate("m.@l1k");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Local part do e-mail n\u00E3o pode come\u00E7ar ou terminar com ponto
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      try { 
        EmailValidator.validate(".A@\"N");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Local part do e-mail n\u00E3o pode come\u00E7ar ou terminar com ponto
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      try { 
        EmailValidator.validate("05..<w@dl1F");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail n\u00E3o pode conter pontos consecutivos
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      try { 
        EmailValidator.validate("I}'tn>!2k(@@Iz");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail n\u00E3o pode conter mais de um '@'
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = EmailValidator.isValid("q.~,N0Jlt_ZPj@");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      try { 
        EmailValidator.validate("@W>xc)bT{jM");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail deve conter exatamente um '@' em posi\u00E7\u00E3o v\u00E1lida
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      try { 
        EmailValidator.validate("Locallpart dowe-ma>l n\u00E3o pode come\u00E7ar ou term`nar com po;to");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail deve conter exatamente um '@' em posi\u00E7\u00E3o v\u00E1lida
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = EmailValidator.isValid("akql");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      try { 
        EmailValidator.validate("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail n\u00E3o pode ser nulo ou vazio
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      try { 
        EmailValidator.validate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // E-mail n\u00E3o pode ser nulo ou vazio
         //
         verifyException("br.ufjf.ead.validator.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EmailValidator emailValidator0 = new EmailValidator();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      boolean boolean0 = EmailValidator.isValid("Evail 3\u00E3o pFde conter mis eum '@'");
      assertFalse(boolean0);
  }
}
