/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 16:57:14 GMT 2026
 */

package br.ufjf.ead.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ead.validator.PasswordValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PasswordValidator_ESTest extends PasswordValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = PasswordValidator.generateSecurePassword(2301);
      assertEquals("9}}0I(j}I99a(0cA9aaIaa}I20}aA9R99j*AR}RI0(ajj9((j}sasjssI0II9Raj0s}}}Rs(Ij9s((AIIRa0(s9ARjsR9(}09(}AAAAAAs0000sjaRIssjaRA(0jRAjR", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = PasswordValidator.evaluateStrength("e");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = PasswordValidator.evaluateStrength("9}}0I(j}I99a(0cA9aaIaa}I20}aA9R99j*AR}RI0(ajj9((j}sasjssI0II9Raj0s}}}Rs(Ij9s((AIIRa0(s9ARjsR9(}09(}AAAAAAs0000sjaRIssjaRA(0jRAjR");
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = PasswordValidator.evaluateStrength("2345678");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = PasswordValidator.evaluateStrength("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = PasswordValidator.evaluateStrength((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      boolean boolean0 = PasswordValidator.isValid("hTgc7LLl");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = PasswordValidator.isValid("K?K3R=8:");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      try { 
        PasswordValidator.validate(":?m>puw;");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Senha deve conter pelo menos 1 letra mai\u00FAscula
         //
         verifyException("br.ufjf.ead.validator.PasswordValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      boolean boolean0 = PasswordValidator.isValid("TgJ1xe[q");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      try { 
        PasswordValidator.validate("password1");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Senha muito comum, escolha outra
         //
         verifyException("br.ufjf.ead.validator.PasswordValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      try { 
        PasswordValidator.validate("9}}0I(j}I99a(0cA9aaIaa}I20}aA9R99j*AR}RI0(ajj9((j}sasjssI0II9Raj0s}}}Rs(Ij9s((AIIRa0(s9ARjsR9(}09(}AAAAAAs0000sjaRIssjaRA(0jRAjR");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Senha deve conter apenas caracteres ASCII imprim\u00EDveis
         //
         verifyException("br.ufjf.ead.validator.PasswordValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      try { 
        PasswordValidator.validate("admin");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Senha deve ter pelo menos 8 caracteres
         //
         verifyException("br.ufjf.ead.validator.PasswordValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      boolean boolean0 = PasswordValidator.isValid(":cM>Puwl");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      try { 
        PasswordValidator.validate((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Senha n\u00E3o pode ser nula ou vazia
         //
         verifyException("br.ufjf.ead.validator.PasswordValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PasswordValidator passwordValidator0 = new PasswordValidator();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = PasswordValidator.generateSecurePassword((-1769));
      assertEquals("c2*jsA90", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      boolean boolean0 = PasswordValidator.isValid("");
      assertFalse(boolean0);
  }
}
