/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 15 17:01:34 GMT 2026
 */

package br.ufjf.ead.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import br.ufjf.ead.exception.InvalidDocumentException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidDocumentException_ESTest extends InvalidDocumentException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidDocumentException invalidDocumentException0 = new InvalidDocumentException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      InvalidDocumentException invalidDocumentException0 = new InvalidDocumentException("", mockThrowable0);
  }
}
